int Damage(int x, int y);
int HiDamage(int x, int y);
void sentou(int HP, int MAXHP, int SP, int MAXSP, int level, int exp, int maxexp, int x);
void GAMEOVER();
void win(int getexp, int getmoney, int exp, int maxexp);
int revelup(int exp, int maxexp);
int Bonus(int revel);
int zenkaihuku(int hp, int maxhp);
int question01suu();
int question01ei();
int question02ei();
int question03ei();
int question04ei();
int question05ei();
int question06ei();
int question07ei();
int question08ei();
int question09ei();
int question10ei();
int question11ei();